python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\ar\convert-mp3-to-text.html examples\convert-mp3-to-text\instructions.match -e lang=ar -o C:\Users\murat\Documents\maestra\working\localization\public\ar\tools\audio-to-text\convert-mp3-to-text.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\da\mp3-til-tekst.html examples\convert-mp3-to-text\instructions.match -e lang=da -o C:\Users\murat\Documents\maestra\working\localization\public\da\vaerktojer\lyd-til-text\konverter-mp3-til-tekst.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\de\mp3-zu-text.html examples\convert-mp3-to-text\instructions.match -e lang=de -o C:\Users\murat\Documents\maestra\working\localization\public\de\werkzeuge\audio-zu-text\konvertieren-sie-mp3-in-text.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\es\convertir-mp3-a-texto.html examples\convert-mp3-to-text\instructions.match -e lang=es -o C:\Users\murat\Documents\maestra\working\localization\public\es\herramientas\audio-a-texto\convertir-mp3-a-texto.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\fi\mp3-tekstiksi.html examples\convert-mp3-to-text\instructions.match -e lang=fi -o C:\Users\murat\Documents\maestra\working\localization\public\fi\tyokalut\audio-en-texte\muunna-mp3-tekstiksi.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\fr\convertir-mp3-en-texte.html examples\convert-mp3-to-text\instructions.match -e lang=fr -o C:\Users\murat\Documents\maestra\working\localization\public\fr\outils\audio-en-texte\convertir-mp3-en-text.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\it\da-mp3-a-testo.html examples\convert-mp3-to-text\instructions.match -e lang=it -o C:\Users\murat\Documents\maestra\working\localization\public\it\strumenti\audio-a-testo\converti-mp3-in-testo.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\ja\convert-mp3-to-text.html examples\convert-mp3-to-text\instructions.match -e lang=ja -o C:\Users\murat\Documents\maestra\working\localization\public\ja\tools\audio-to-text\convert-mp3-to-text.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\ko\convert-mp3-to-text.html examples\convert-mp3-to-text\instructions.match -e lang=ko -o C:\Users\murat\Documents\maestra\working\localization\public\ko\tools\audio-to-text\convert-mp3-to-text.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\pl\mp3-na-tekst.html examples\convert-mp3-to-text\instructions.match -e lang=pl -o C:\Users\murat\Documents\maestra\working\localization\public\pl\narzedzia\audio-na-tekst\konwertuj-mp3-na-tekst.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\pt\mp3-para-texto.html examples\convert-mp3-to-text\instructions.match -e lang=pt -o C:\Users\murat\Documents\maestra\working\localization\public\pt\ferramentas\transcricao-de-audio\converter-mp3-para-texto.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\sv\convert-mp3-to-text.html examples\convert-mp3-to-text\instructions.match -e lang=sv -o C:\Users\murat\Documents\maestra\working\localization\public\sv\verktyg\audio-to-text\convert-mp3-to-text.html
python main.py examples\convert-mp3-to-text\target_index.html ..\..\working\rebrand\public\zh\convert-mp3-to-text.html examples\convert-mp3-to-text\instructions.match -e lang=zh -o C:\Users\murat\Documents\maestra\working\localization\public\zh\tools\audio-to-text\convert-mp3-to-text.html
npx prettier --write C:\Users\murat\Documents\maestra\working\localization\public\ar\tools\audio-to-text\convert-mp3-to-text.html C:\Users\murat\Documents\maestra\working\localization\public\da\vaerktojer\lyd-til-text\konverter-mp3-til-tekst.html C:\Users\murat\Documents\maestra\working\localization\public\de\werkzeuge\audio-zu-text\konvertieren-sie-mp3-in-text.html C:\Users\murat\Documents\maestra\working\localization\public\es\herramientas\audio-a-texto\convertir-mp3-a-texto.html C:\Users\murat\Documents\maestra\working\localization\public\fi\tyokalut\audio-en-texte\muunna-mp3-tekstiksi.html C:\Users\murat\Documents\maestra\working\localization\public\fr\outils\audio-en-texte\convertir-mp3-en-text.html C:\Users\murat\Documents\maestra\working\localization\public\it\strumenti\audio-a-testo\converti-mp3-in-testo.html C:\Users\murat\Documents\maestra\working\localization\public\ja\tools\audio-to-text\convert-mp3-to-text.html C:\Users\murat\Documents\maestra\working\localization\public\ko\tools\audio-to-text\convert-mp3-to-text.html C:\Users\murat\Documents\maestra\working\localization\public\pl\narzedzia\audio-na-tekst\konwertuj-mp3-na-tekst.html C:\Users\murat\Documents\maestra\working\localization\public\pt\ferramentas\transcricao-de-audio\converter-mp3-para-texto.html C:\Users\murat\Documents\maestra\working\localization\public\sv\verktyg\audio-to-text\convert-mp3-to-text.html C:\Users\murat\Documents\maestra\working\localization\public\zh\tools\audio-to-text\convert-mp3-to-text.html