python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\ar\transcribe-video-to-text.html examples\video-to-text\instructions.match -e lang=ar -o C:\Users\murat\Documents\maestra\working\localization\public\ar\tools\video-to-text\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\da\video-til-tekst.html examples\video-to-text\instructions.match -e lang=da -o C:\Users\murat\Documents\maestra\working\localization\public\da\vaerktojer\video-til-tekst\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\de\video-zu-text.html examples\video-to-text\instructions.match -e lang=de -o C:\Users\murat\Documents\maestra\working\localization\public\de\werkzeuge\video-zu-text\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\es\transcribe-video-a-texto.html examples\video-to-text\instructions.match -e lang=es -o C:\Users\murat\Documents\maestra\working\localization\public\es\herramientas\video-a-texto\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\fi\video-tekstiksi.html examples\video-to-text\instructions.match -e lang=fi -o C:\Users\murat\Documents\maestra\working\localization\public\fi\tyokalut\video-tekstiksi\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\fr\transcrire-video-en-texte.html examples\video-to-text\instructions.match -e lang=fr -o C:\Users\murat\Documents\maestra\working\localization\public\fr\outils\video-en-texte\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\it\da-video-a-testo.html examples\video-to-text\instructions.match -e lang=it -o C:\Users\murat\Documents\maestra\working\localization\public\it\strumenti\video-in-testo\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\ja\transcribe-video-to-text.html examples\video-to-text\instructions.match -e lang=ja -o C:\Users\murat\Documents\maestra\working\localization\public\ja\tools\video-to-text\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\ko\transcribe-video-to-text.html examples\video-to-text\instructions.match -e lang=ko -o C:\Users\murat\Documents\maestra\working\localization\public\ko\tools\video-to-text\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\pl\wideo-na-tekst.html examples\video-to-text\instructions.match -e lang=pl -o C:\Users\murat\Documents\maestra\working\localization\public\pl\narzedzia\wideo-na-tekst\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\pt\transcricao-de-video.html examples\video-to-text\instructions.match -e lang=pt -o C:\Users\murat\Documents\maestra\working\localization\public\pt\ferramentas\video-para-texto\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\sv\transcribe-video-to-text.html examples\video-to-text\instructions.match -e lang=sv -o C:\Users\murat\Documents\maestra\working\localization\public\sv\verktyg\video-to-text\index.html
python main.py examples\video-to-text\target_index.html ..\..\working\rebrand\public\zh\transcribe-video-to-text.html examples\video-to-text\instructions.match -e lang=zh -o C:\Users\murat\Documents\maestra\working\localization\public\zh\tools\video-to-text\index.html
npx prettier --write C:\Users\murat\Documents\maestra\working\localization\public\ar\tools\video-to-text\index.html C:\Users\murat\Documents\maestra\working\localization\public\da\vaerktojer\video-til-tekst\index.html C:\Users\murat\Documents\maestra\working\localization\public\de\werkzeuge\video-zu-text\index.html C:\Users\murat\Documents\maestra\working\localization\public\es\herramientas\video-a-texto\index.html C:\Users\murat\Documents\maestra\working\localization\public\fi\tyokalut\video-tekstiksi\index.html C:\Users\murat\Documents\maestra\working\localization\public\fr\outils\video-en-texte\index.html C:\Users\murat\Documents\maestra\working\localization\public\it\strumenti\video-in-testo\index.html C:\Users\murat\Documents\maestra\working\localization\public\ja\tools\video-to-text\index.html C:\Users\murat\Documents\maestra\working\localization\public\ko\tools\video-to-text\index.html C:\Users\murat\Documents\maestra\working\localization\public\pl\narzedzia\wideo-na-tekst\index.html C:\Users\murat\Documents\maestra\working\localization\public\pt\ferramentas\video-para-texto\index.html C:\Users\murat\Documents\maestra\working\localization\public\sv\verktyg\video-to-text\index.html C:\Users\murat\Documents\maestra\working\localization\public\zh\tools\video-to-text\index.html