python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\ar\video-translator-online.html examples\video-translator\instructions.match -e lang=ar -o ..\..\working\localization\public\ar\tools\video-translator\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\da\video-oversaetter-online.html examples\video-translator\instructions.match -e lang=da -o ..\..\working\localization\public\da\vaerktojer\video-oversaetter\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\de\videoubersetzer.html examples\video-translator\instructions.match -e lang=de -o ..\..\working\localization\public\de\werkzeuge\videoubersetzer\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\fi\video-kaantaja.html examples\video-translator\instructions.match -e lang=fi -o ..\..\working\localization\public\fi\tyokalut\video-kaantaja\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\fr\traduire-video.html examples\video-translator\instructions.match -e lang=fr -o ..\..\working\localization\public\fr\outils\traducteur-video\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\it\traduttore-video.html examples\video-translator\instructions.match -e lang=it -o ..\..\working\localization\public\it\strumenti\traduttore-video\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\ja\video-translator-online.html examples\video-translator\instructions.match -e lang=ja -o ..\..\working\localization\public\ja\tools\video-translator\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\ko\video-translator-online.html examples\video-translator\instructions.match -e lang=ko -o ..\..\working\localization\public\ko\tools\video-translator\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\pl\tlumacz-wideo.html examples\video-translator\instructions.match -e lang=pl -o ..\..\working\localization\public\pl\narzedzia\tlumacz-wideo\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\pt\tradutor-de-video.html examples\video-translator\instructions.match -e lang=pt -o ..\..\working\localization\public\pt\ferramentas\tradutor-de-video\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\sv\video-translator-online.html examples\video-translator\instructions.match -e lang=sv -o ..\..\working\localization\public\sv\verktyg\video-translator\index.html
python main.py examples\video-translator\target_index.html ..\..\working\rebrand\public\zh\video-translator-online.html examples\video-translator\instructions.match -e lang=zh -o ..\..\working\localization\public\zh\tools\video-translator\index.html

npx prettier --write ..\..\working\localization\public\ar\tools\video-translator\index.html ..\..\working\localization\public\da\vaerktojer\video-oversaetter\index.html ..\..\working\localization\public\de\werkzeuge\videoubersetzer\index.html ..\..\working\localization\public\fi\tyokalut\video-kaantaja\index.html ..\..\working\localization\public\fr\outils\traducteur-video\index.html ..\..\working\localization\public\it\strumenti\traduttore-video\index.html ..\..\working\localization\public\ja\tools\video-translator\index.html ..\..\working\localization\public\ko\tools\video-translator\index.html ..\..\working\localization\public\pl\narzedzia\tlumacz-wideo\index.html ..\..\working\localization\public\pt\ferramentas\tradutor-de-video\index.html ..\..\working\localization\public\sv\verktyg\video-translator\index.html ..\..\working\localization\public\zh\tools\video-translator\index.html