python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\ar\convert-mp4-to-text.html examples\convert-mp4-to-text\instructions.match -e lang=ar -o C:\Users\murat\Documents\maestra\working\localization\public\ar\tools\video-to-text\convert-mp4-to-text.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\da\mp4-til-tekst.html examples\convert-mp4-to-text\instructions.match -e lang=da -o C:\Users\murat\Documents\maestra\working\localization\public\da\vaerktojer\video-til-tekst\konvertere-mp4-til-tekst.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\de\mp4-zu-text.html examples\convert-mp4-to-text\instructions.match -e lang=de -o C:\Users\murat\Documents\maestra\working\localization\public\de\werkzeuge\video-zu-text\konvertieren-sie-mp4-in-text.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\es\convertir-mp4-a-texto.html examples\convert-mp4-to-text\instructions.match -e lang=es -o C:\Users\murat\Documents\maestra\working\localization\public\es\herramientas\video-a-texto\convertir-mp4-a-texto.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\fi\mp4-tekstiksi.html examples\convert-mp4-to-text\instructions.match -e lang=fi -o C:\Users\murat\Documents\maestra\working\localization\public\fi\tyokalut\video-tekstiksi\muuntaa-mp4-tekstiksi.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\fr\convertir-mp4-en-texte.html examples\convert-mp4-to-text\instructions.match -e lang=fr -o C:\Users\murat\Documents\maestra\working\localization\public\fr\outils\video-en-texte\convertir-mp4-en-texte.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\it\da-mp4-a-testo.html examples\convert-mp4-to-text\instructions.match -e lang=it -o C:\Users\murat\Documents\maestra\working\localization\public\it\strumenti\video-in-testo\convertire-mp4-in-testo.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\ja\convert-mp4-to-text.html examples\convert-mp4-to-text\instructions.match -e lang=ja -o C:\Users\murat\Documents\maestra\working\localization\public\ja\tools\video-to-text\convert-mp4-to-text.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\ko\convert-mp4-to-text.html examples\convert-mp4-to-text\instructions.match -e lang=ko -o C:\Users\murat\Documents\maestra\working\localization\public\ko\tools\video-to-text\convert-mp4-to-text.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\pl\mp4-na-tekst.html examples\convert-mp4-to-text\instructions.match -e lang=pl -o C:\Users\murat\Documents\maestra\working\localization\public\pl\narzedzia\wideo-na-tekst\przekonwertowac-mp4-na-tekst.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\pt\mp4-para-texto.html examples\convert-mp4-to-text\instructions.match -e lang=pt -o C:\Users\murat\Documents\maestra\working\localization\public\pt\ferramentas\video-para-texto\converter-mp4-para-texto.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\sv\convert-mp4-to-text.html examples\convert-mp4-to-text\instructions.match -e lang=sv -o C:\Users\murat\Documents\maestra\working\localization\public\sv\verktyg\video-to-text\convert-mp4-to-text.html
python main.py examples\convert-mp4-to-text\target_index.html ..\..\working\rebrand\public\zh\convert-mp4-to-text.html examples\convert-mp4-to-text\instructions.match -e lang=zh -o C:\Users\murat\Documents\maestra\working\localization\public\zh\tools\video-to-text\convert-mp4-to-text.html
npx prettier --write C:\Users\murat\Documents\maestra\working\localization\public\ar\tools\video-to-text\convert-mp4-to-text.html C:\Users\murat\Documents\maestra\working\localization\public\da\vaerktojer\video-til-tekst\konvertere-mp4-til-tekst.html C:\Users\murat\Documents\maestra\working\localization\public\de\werkzeuge\video-zu-text\konvertieren-sie-mp4-in-text.html C:\Users\murat\Documents\maestra\working\localization\public\es\herramientas\video-a-texto\convertir-mp4-a-texto.html C:\Users\murat\Documents\maestra\working\localization\public\fi\tyokalut\video-tekstiksi\muuntaa-mp4-tekstiksi.html C:\Users\murat\Documents\maestra\working\localization\public\fr\outils\video-en-texte\convertir-mp4-en-texte.html C:\Users\murat\Documents\maestra\working\localization\public\it\strumenti\video-in-testo\convertire-mp4-in-testo.html C:\Users\murat\Documents\maestra\working\localization\public\ja\tools\video-to-text\convert-mp4-to-text.html C:\Users\murat\Documents\maestra\working\localization\public\ko\tools\video-to-text\convert-mp4-to-text.html C:\Users\murat\Documents\maestra\working\localization\public\pl\narzedzia\wideo-na-tekst\przekonwertowac-mp4-na-tekst.html C:\Users\murat\Documents\maestra\working\localization\public\pt\ferramentas\video-para-texto\converter-mp4-para-texto.html C:\Users\murat\Documents\maestra\working\localization\public\sv\verktyg\video-to-text\convert-mp4-to-text.html C:\Users\murat\Documents\maestra\working\localization\public\zh\tools\video-to-text\convert-mp4-to-text.html